name: git co authors

on:
  workflow_dispatch:
    inputs:
  push:
    branches:
      - master
      - develop
jobs:
  build:
    env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix: 
        os: [ubuntu-latest, windows-latest]

    steps:
    - name: Install dependencies for Linux
      run: sudo apt-get install libgtk-3-dev
      if: matrix.os == 'ubuntu-latest'
    - uses: actions/checkout@v1
    - name: Checkout submodules
      run: git submodule update --init
    - uses: actions/setup-python@v1
    - name: Install ninja
      run: python -m pip install ninja==1.9.0.post1
    - name: Install meson
      run: python -m pip install meson==0.53.2
    - name: Build libui
      run: |
         meson setup build -Ddefault_library=static
         meson build -C build/
      working-directory: libui
    - name: Build
      run: |
         meson setup build
         meson build -C build/
